### ISSUE TITLE
Lies, Damned Lies, and Benchmarks

### ISSUE THREAD

**Issue by ramsey** [ramsey/uuid-benchmark#2]
I considered creating a wiki page for this, but I think an issue might be the best way to track comments and discussion on this.

---

Here's the output of running `php uuid-benchmark.php` against version 5b1a69c235466ab3632208d8f7042f477c460d8c of the benchmark script:

```
            PECL | 0.0280 sec/10000 | 0.0000028 sec/one
         RHUMSAA | 0.0430 sec/10000 | 0.0000043 sec/one
     RAMSEY-PECL | 0.1660 sec/10000 | 0.0000166 sec/one
   RAMSEY-NOPECL | 0.0460 sec/10000 | 0.0000046 sec/one
RAMSEY-RANDOMLIB | 0.4310 sec/10000 | 0.0000431 sec/one
     RAMSEY-PHP7 | 0.0520 sec/10000 | 0.0000052 sec/one
```

It's clear from this benchmark that we gain nothing by providing `PeclUuidFactory`. In fact, we lose performance. The only thing we gain is better randomization with access to `/dev/urandom` or `/dev/random`. Without pecl-uuid, the ramsey/uuid library at version 3.0 appears to perform right on par with it's predecessor at version 2.8, and I think that's a win for us.

I say we drop default support for pecl-uuid. I don't want people to get fooled into thinking it's a better option for the sake of performance. The gain with pecl-uuid support in this library is better randomization. Maybe we spin that off into a separate repository for those who want to use it?

I think it's also clear that we need to add a generator for PHP 7's `generate_bytes()`. While the performance is slightly less than our default, it does provide much better/safer randomization, and I think it should be the default if we detect the library is running on PHP 7.

Thoughts?

**Comment by ramsey** [comment]
Tapping @jaymecd, @aztech-dev, and @marijn for comment.

Referencing https://github.com/ramsey/uuid/issues/56

**Comment by ramsey** [comment]
As @ircmaxell suggested on https://github.com/ramsey/uuid/issues/56, I'm now using a medium-strength generator in the benchmark script. We'll update ramsey/uuid to use this by default in the `RandomLibAdapter`.

Here are the results of a benchmark run after updating to use a medium-strength generator (version 1502cd38bbebb5b778d9d6d4b7bb33f45ed572fa):

```
            PECL | 0.0270 sec/10000 | 0.0000027 sec/one
         RHUMSAA | 0.0430 sec/10000 | 0.0000043 sec/one
     RAMSEY-PECL | 0.1610 sec/10000 | 0.0000161 sec/one
   RAMSEY-NOPECL | 0.0480 sec/10000 | 0.0000048 sec/one
RAMSEY-RANDOMLIB | 0.6680 sec/10000 | 0.0000668 sec/one
     RAMSEY-PHP7 | 0.0540 sec/10000 | 0.0000054 sec/one
```

**Comment by jaymecd** [comment]
RAMSEY-PECL really doesn't worth `4x` performance drop. 

To make final decision, would it be be fair to have an opposite benchmark for `Uuid::fromString`?
As that is also plays important role, eg. dto object hydration.

**Comment by fabre-thibaud** [comment]
@ramsey Did you run the PECL benchmark against (the admitedly bad) https://github.com/ramsey/uuid/pull/58 or current 3.0-alpha1 ?

As I mentionned on the P/R, the issue with the current design is as follows:
- Pure PHP UUID generation happens by generating all the fields for a UUID, and converting those to string as needed (which is the most frequent use case)
- PECL based generation works exactly the other way around, we have to parse a string into fields to match the model of the PHP generated UUID's, which is where the performance penalty happens.

I don't see many solutions to that problem:
- Implement something akin to my currently open P/R (improving it as needed -- I'm open to any suggestions) with lazy parsing -- but I haven't been able to find a more elegant solution (be it composition or inheritance)
- Split UuidInterface into two, one providing only a toString() method and another providing all the extra convenience methods (and extending the light interface) -- the PECL factory implementation could then only return a UUID class implementing only the light interface, and other factories would return another UUID class implementing the fat interface.

I sort of like solution two, but it means the PECL factory is not BC and cannot be used as a dropin replacement of native factories. It does however preserve the performance benefits of using PECL and would match most use cases.

**Comment by fabre-thibaud** [comment]
PS. I'll update https://github.com/ramsey/uuid/pull/58 tonight to reflect option 2 as it will give a better view of what I'm thinking.

**Comment by ramsey** [comment]
I've created a PR to support PHP 7's `random_bytes()`. Please check it out and offer any feedback:

https://github.com/ramsey/uuid/pull/67

**Comment by ramsey** [comment]
@aztech-dev, I forgot to answer your question. Sorry. I ran the benchmark against 3.0.0-alpha1 and not https://github.com/ramsey/uuid/pull/58.

I'll add a 3rd option to your list of solutions:
- Figure out a way to treat pecl-uuid as a generator.

Take a look at https://github.com/ramsey/uuid-benchmark/commit/bbc62ab6fd9a11d43fb031d02636c108e787a87e. In this commit, I've added a new random generator for handling `uuid4()` generation with pecl-uuid. Since pecl-uuid has `uuid_parse()`, we can turn the string UUID that `uuid_create()` makes into bytes and use it as a random generator.

Here are the results of a benchmark run with `PeclRandomGenerator` (run on PHP 5.6.11):

```
                 PECL | 0.0380 sec/10000 | 0.0000038 sec/one
              RHUMSAA | 0.1870 sec/10000 | 0.0000187 sec/one
          RAMSEY-PECL | 0.4320 sec/10000 | 0.0000432 sec/one
        RAMSEY-NOPECL | 0.2400 sec/10000 | 0.0000240 sec/one
     RAMSEY-RANDOMLIB | 1.9920 sec/10000 | 0.0001992 sec/one
RAMSEY-PECL-GENERATOR | 0.2870 sec/10000 | 0.0000287 sec/one
```

Note the new "RAMSEY-PECL-GENERATOR" line. It's still less performant than pecl-uuid by itself and less performant than "RAMSEY-NOPECL" but not by much. By contrast, it's much better than "RAMSEY-PECL."

Thoughts?

I'll mention that this doesn't solve a `uuid1()` scenario, since pecl-uuid also provides the ability to create version 1 UUIDs. I've been tinkering with how to split the time-based UUID generating functionality of `UuidFactory::uuid1()` into a set of Time Generator classes that work similarly to how the `RandomGeneratorInterface` family works, but I can't seem to come up with anything elegant.

To compare with the results of the same benchmarks above run on PHP 7.0.0-dev on the same machine:

```
                 PECL | 0.0280 sec/10000 | 0.0000028 sec/one
              RHUMSAA | 0.0420 sec/10000 | 0.0000042 sec/one
          RAMSEY-PECL | 0.1580 sec/10000 | 0.0000158 sec/one
        RAMSEY-NOPECL | 0.0460 sec/10000 | 0.0000046 sec/one
     RAMSEY-RANDOMLIB | 0.6490 sec/10000 | 0.0000649 sec/one
          RAMSEY-PHP7 | 0.0620 sec/10000 | 0.0000062 sec/one
RAMSEY-PECL-GENERATOR | 0.0810 sec/10000 | 0.0000081 sec/one
```

**Comment by ramsey** [comment]
## Version 1 UUID Benchmarks

I put together some benchmarks for generating **version 1** UUIDs, as well (see https://github.com/ramsey/uuid-benchmark/commit/0874dae3dc32c749d480fd6f07765980da93f235).

These benchmarks use intended to show version 1 UUID generation in pecl-uuid, rhumsaa/uuid, ramsey/uuid with default time generator, and ramsey/uuid with pecl-uuid time generator. To do this, I'm using the [pecl-generator branch](https://github.com/ramsey/uuid/tree/pecl-generator) of ramsey/uuid.

For some odd reason, Composer wouldn't let me install `ramsey/uuid dev-pecl-generator` at the same time as rhumsaa/uuid, even though I can have `ramsey/uuid 3.0.0-alpha1` installed at the same time as rhumsaa/uuid. Go figure. I had to switch back-and-forth to generate these benchmarks.

To get the "RAMSEY-3.0.0-ALPHA1" benchmarks, I switched Composer back to ramsey/uuid at 3.0.0-alpha1.

Both "RAMSEY-DEFAULT-GENERATOR" and "RAMSEY-PECL-GENERATOR" are using the `pecl-generator` branch as their source.

Note that rhumsaa/uuid seems way off. What changed between rhumsaa/uuid and ramsey/uuid to make such a dramatic difference in the way version 1 UUIDs are generated? Nothing jumps out at me as being extremely different in the code that is running to generate them.

**Version 1** UUIDs in PHP 5.6.11:

```
                    PECL | 0.0890 sec/10000 | 0.0000089 sec/one
                 RHUMSAA | 20.6200 sec/10000 | 0.0020620 sec/one
     RAMSEY-3.0.0-ALPHA1 | 0.4950 sec/10000 | 0.0000495 sec/one
RAMSEY-DEFAULT-GENERATOR | 0.5300 sec/10000 | 0.0000530 sec/one
   RAMSEY-PECL-GENERATOR | 0.3680 sec/10000 | 0.0000368 sec/one
```

**Version 1** UUIDs in PHP 7.0.0-dev:

```
                    PECL | 0.0690 sec/10000 | 0.0000069 sec/one
                 RHUMSAA | 22.9590 sec/10000 | 0.0022959 sec/one
     RAMSEY-3.0.0-ALPHA1 | 0.1770 sec/10000 | 0.0000177 sec/one
RAMSEY-DEFAULT-GENERATOR | 0.2230 sec/10000 | 0.0000223 sec/one
   RAMSEY-PECL-GENERATOR | 0.1410 sec/10000 | 0.0000141 sec/one
```

**Comment by fabre-thibaud** [comment]
Nice, the generator option is pretty nifty. I was supposed to work on option 2 but never got around to it, and I guess I never will now :)

Regarding the time difference, I had to profile to find the root issue: getIfConfig() is called 10K times with Rhumsaa, vs once with Ramsey.

The issue was fixed with 2.8.1, but Packagist apparently never picked up the release, hence the huge time difference in benchmarks.

**Comment by ramsey** [comment]
Doh! Thanks!

That's related to me creating the rhumsaa-uuid GitHub repository. I'll backport the 2.8.1 tag into that repo now.

**Comment by ramsey** [comment]
Okay. Now my tests are properly using version 2.8.2 of rhumsaa/uuid, and this looks better.

**Version 1** UUIDs on PHP 5.6.11:

```
                    PECL | 0.0950 sec/10000 | 0.0000095 sec/one
                 RHUMSAA | 0.2020 sec/10000 | 0.0000202 sec/one
     RAMSEY-3.0.0-ALPHA1 | 0.4880 sec/10000 | 0.0000488 sec/one
RAMSEY-DEFAULT-GENERATOR | 0.4680 sec/10000 | 0.0000468 sec/one
   RAMSEY-PECL-GENERATOR | 0.3780 sec/10000 | 0.0000378 sec/one
```

**Version 1** UUIDs on PHP 7.0.0-dev:

```
                    PECL | 0.0810 sec/10000 | 0.0000081 sec/one
                 RHUMSAA | 0.0470 sec/10000 | 0.0000047 sec/one
     RAMSEY-3.0.0-ALPHA1 | 0.1700 sec/10000 | 0.0000170 sec/one
RAMSEY-DEFAULT-GENERATOR | 0.1710 sec/10000 | 0.0000171 sec/one
   RAMSEY-PECL-GENERATOR | 0.1360 sec/10000 | 0.0000136 sec/one
```

**Comment by ramsey** [comment]
In my latest update to the benchmark scripts (90638a781ea4e5278e71b97303e040cd14e5c380), I'm using the latest 3.0.0-alpha3 of ramsey/uuid.

At this point, we're still seeing a difference between raw pecl-uuid and ramsey/uuid using pecl-uuid, but I think this difference is acceptable. Thoughts?

Here are the results:

## Benchmarks on PHP 5.6.11

### Version 1 UUID

```
                    PECL | 0.0970 sec/10000 | 0.0000097 sec/one
                 RHUMSAA | 0.2190 sec/10000 | 0.0000219 sec/one
          RAMSEY-DEFAULT | 0.4880 sec/10000 | 0.0000488 sec/one
             RAMSEY-PECL | 0.3890 sec/10000 | 0.0000389 sec/one
```

### Version 4 UUID

_rhumsaa/uuid defaulted to `openssl_random_pseudo_bytes()` in this run._

```
                 PECL | 0.0390 sec/10000 | 0.0000039 sec/one
              RHUMSAA | 0.1830 sec/10000 | 0.0000183 sec/one
       RAMSEY-OPENSSL | 0.3080 sec/10000 | 0.0000308 sec/one
        RAMSEY-MTRAND | 0.4430 sec/10000 | 0.0000443 sec/one
          RAMSEY-PECL | 0.2970 sec/10000 | 0.0000297 sec/one
     RAMSEY-RANDOMLIB | 2.0420 sec/10000 | 0.0002042 sec/one
```

## Benchmarks on PHP 7.0.0-dev

### Version 1 UUID

```
                    PECL | 0.0690 sec/10000 | 0.0000069 sec/one
                 RHUMSAA | 0.0480 sec/10000 | 0.0000048 sec/one
          RAMSEY-DEFAULT | 0.1380 sec/10000 | 0.0000138 sec/one
             RAMSEY-PECL | 0.1420 sec/10000 | 0.0000142 sec/one
```

### Version 4 UUID

_rhumsaa/uuid defaulted to `openssl_random_pseudo_bytes()` in this run._

```
                 PECL | 0.0280 sec/10000 | 0.0000028 sec/one
              RHUMSAA | 0.0400 sec/10000 | 0.0000040 sec/one
          RAMSEY-PHP7 | 0.1110 sec/10000 | 0.0000111 sec/one
       RAMSEY-OPENSSL | 0.0470 sec/10000 | 0.0000047 sec/one
        RAMSEY-MTRAND | 0.0600 sec/10000 | 0.0000060 sec/one
          RAMSEY-PECL | 0.0810 sec/10000 | 0.0000081 sec/one
     RAMSEY-RANDOMLIB | 0.6530 sec/10000 | 0.0000653 sec/one
```

**Comment by fabre-thibaud** [comment]
Do you have xdebug enabled ? :)

**Comment by ramsey** [comment]
Ah. Good call. Here we are on 5.6.11 without Xdebug enabled. Xdebug doesn't yet work on PHP 7, so the earlier benchmarks on PHP 7.0.0-dev are still good.

## PHP 5.6.11

### Version 1 UUID

```
                    PECL | 0.0770 sec/10000 | 0.0000077 sec/one
                 RHUMSAA | 0.0930 sec/10000 | 0.0000093 sec/one
          RAMSEY-DEFAULT | 0.2220 sec/10000 | 0.0000222 sec/one
             RAMSEY-PECL | 0.2090 sec/10000 | 0.0000209 sec/one
```

### Version 4 UUID

```
                 PECL | 0.0300 sec/10000 | 0.0000030 sec/one
              RHUMSAA | 0.0750 sec/10000 | 0.0000075 sec/one
       RAMSEY-OPENSSL | 0.1450 sec/10000 | 0.0000145 sec/one
        RAMSEY-MTRAND | 0.1260 sec/10000 | 0.0000126 sec/one
          RAMSEY-PECL | 0.1270 sec/10000 | 0.0000127 sec/one
     RAMSEY-RANDOMLIB | 0.9230 sec/10000 | 0.0000923 sec/one
```

**Comment by fabre-thibaud** [comment]
Interesting... your benches are _slower_ with OpenSSL. I'm getting pretty much the same results running on PHP v5.5.9, with the exception of OpenSSL being wildly faster than yours:

### Version 4 UUID

```
             PECL | 0.0370 sec/10000 | 0.0000037 sec/one
  RHUMSAA-OPENSSL | 0.0570 sec/10000 | 0.0000057 sec/one
   RHUMSAA-MTRAND | 0.0980 sec/10000 | 0.0000098 sec/one
   RAMSEY-OPENSSL | 0.0780 sec/10000 | 0.0000078 sec/one
    RAMSEY-MTRAND | 0.1120 sec/10000 | 0.0000112 sec/one
      RAMSEY-PECL | 0.1130 sec/10000 | 0.0000113 sec/one
 RAMSEY-RANDOMLIB | 0.6970 sec/10000 | 0.0000697 sec/one
```

(I slightly modified the benchmark to run two passes on Rhumsaa, with and without OpenSSL)
